import type { ItemActionResult } from "./Inventory.js";
import type { CardDefinition, CardPlayResolution } from "./CardGame.js";
export declare class Effects {
    private static readonly MAX_ITEM_ANIMATIONS_PER_TYPE;
    private static readonly SOUND_STORAGE_KEY;
    private static readonly COMBAT_ITEMS;
    private static readonly CRAFT_ITEMS;
    private static readonly RARE_ITEMS;
    private static soundEnabled;
    private static audioContext;
    static initialize(soundSwitch: HTMLInputElement): void;
    static playItemAction(result: ItemActionResult, sourceElement: HTMLElement | null, actionSeed: number): void;
    static showAreaExplosion(map: HTMLElement, seed: number): void;
    private static areaExplosionSeed;
    static showFightOutcome(board: HTMLElement, outcome: "Victory" | "Defeated"): void;
    static showSpentFightCard(card: HTMLElement): void;
    static playFightCard(resolution: CardPlayResolution, cardElement: HTMLElement | null, monsterPortraitElement: HTMLElement | null, playerPortraitElement: HTMLElement | null, monsterHealthIcon: HTMLElement | null, playerHealthIcon: HTMLElement | null, monsterShieldArea: HTMLElement | null, playerShieldArea: HTMLElement | null, monsterName: string): Promise<void>;
    static dealFightCards(cardElements: HTMLElement[], owner: "player" | "monster", round: number): void;
    static sweepFightCards(cardElements: HTMLElement[]): Promise<void>;
    private static getType;
    private static showChanges;
    private static floatItem;
    static itemFlightStartOffset(actionSeed: number, itemName: string, itemIndex: number, typeIndex: number, spreadX: number, spreadY: number): {
        x: number;
        y: number;
    };
    private static flightStreamSeed;
    private static flightSeed;
    private static stringSeed;
    private static fightCardVariation;
    private static monsterReadableAngle;
    private static animateBlockingCard;
    private static flipMonsterCard;
    private static animateShieldHits;
    private static animateExhaustedShieldReturn;
    private static animateEffectBadge;
    private static animateDamagedBadge;
    private static animateShieldValue;
    private static findShieldElement;
    private static floatFightText;
    private static describeFightEffect;
    static createCardEffectIcons(card: CardDefinition): HTMLElement;
    static createCardArtwork(card: CardDefinition): HTMLElement;
    private static appendCardEffectIcon;
    private static cardContents;
    private static textElement;
    private static animationFinished;
    private static pause;
    private static capitalize;
    private static centerOf;
    private static playSound;
    private static vibrate;
}
//# sourceMappingURL=Effects.d.ts.map