import type { ItemActionResult } from "./Inventory.js";
import type { CardDefinition, CardPlayResolution } from "./CardGame.js";
export declare class Effects {
    private static readonly SOUND_STORAGE_KEY;
    private static readonly COMBAT_ITEMS;
    private static readonly CRAFT_ITEMS;
    private static readonly RARE_ITEMS;
    private static soundEnabled;
    private static audioContext;
    static initialize(soundSwitch: HTMLInputElement): void;
    static playItemAction(result: ItemActionResult, sourceElement: HTMLElement | null): void;
    static showFightRound(board: HTMLElement, remainingRounds: number): void;
    static showFightDefeated(board: HTMLElement): void;
    static showSpentFightCard(card: HTMLElement): void;
    static playFightCard(resolution: CardPlayResolution, cardElement: HTMLElement | null, monsterPortraitElement: HTMLElement | null, playerPortraitElement: HTMLElement | null, monsterShieldArea: HTMLElement | null, playerShieldArea: HTMLElement | null, monsterName: string): Promise<void>;
    static dealFightCards(deckElement: HTMLElement, cardElements: HTMLElement[]): void;
    static sweepFightCards(cardElements: HTMLElement[]): Promise<void>;
    private static getType;
    private static showChanges;
    private static floatText;
    private static animateBlockingCard;
    private static flipMonsterCard;
    private static animateShieldHits;
    private static animateEffectBadge;
    private static animateShieldValue;
    private static findShieldElement;
    private static floatFightText;
    private static describeFightEffect;
    static createCardEffectIcons(card: CardDefinition): HTMLElement;
    private static appendCardEffectIcon;
    private static cardContents;
    private static textElement;
    private static animationFinished;
    private static pause;
    private static capitalize;
    private static centerOf;
    private static playSound;
    private static vibrate;
}
//# sourceMappingURL=Effects.d.ts.map