import { Coordinates } from "./Coordinates.js";
import { Inventory } from "./Inventory.js";
import type { ItemTakingSummary } from "./ItemTakingSummary.js";
import type { Map } from "./Map.js";
export declare class FightView {
    private itemTakingSummary;
    private inventory;
    private coordinates;
    private map;
    private overlay;
    private game;
    private victoryApplied;
    private sourceElement;
    private dealtRound;
    private shownExchange;
    private animating;
    private shownMonsterHealth;
    private shownPlayerHealth;
    private autoCloseTimer;
    constructor(itemTakingSummary: ItemTakingSummary, inventory: Inventory, coordinates: Coordinates, map: Map);
    open(): void;
    private renderMissingYarrow;
    private startGame;
    private render;
    private createFightDeck;
    private createHand;
    private createMonsterHand;
    private createIdentity;
    private createFighterDisplay;
    private createHealthDisplay;
    private createCombatants;
    private createPortrait;
    private playPlayerCard;
    private playCardEffects;
    private chooseMonsterCardElement;
    private syncFightState;
    private finishFight;
    private sweepBoardCards;
    private updateHealthMeter;
    private applyVictory;
    private close;
    private requestClose;
    private button;
    private capitalize;
    private turnStatus;
    private showRoundEffect;
}
//# sourceMappingURL=FightView.d.ts.map